server:
    port: 10031

spring:
    profiles: dev
    data:

elasticsearch:
    host: 193.168.201.85
    port: 9300
    indexName: cloudx_web_v3
    typeName: T_EVENT_LOG
    cluster:
        name: cloudx_web